spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: a54357412
#    driver-class-name: com.mysql.jdbc.Driver

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

ucloud:
  ufile:
    private-key: 8973e061-49a6-415a-857b-b873f26afd93
    public-key: TOKEN_a0c42a3c-3d2b-4789-9d4c-071d3834c6df
    bucket-name: abstract-culture
    region: cn-bj
    suffix: ufileos.com
    expires: 315360000

github:
  client:
    id: 7ec7112452d3904f4082
    secret: ec117b3ff403077da0400372e11147031009cca8
  redirect:
    uri: http://localhost:8080/callback


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.dennis.blog.mapper
  mapper-locations: classpath:mapper/*.xml


pagehelper:
  helperDialect: mysql

